//go:build ignore

// This program generates cgo_flags_generated.go with the correct -I and -L
// paths derived from the OPENVINO_GENAI_ROOT environment variable.
//
// Usage:
//
//	set OPENVINO_GENAI_ROOT=C:\path\to\openvino_genai_windows_...\openvino_genai_windows_...
//	go generate ./openvino/...
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
)

func main() {
	root := os.Getenv("OPENVINO_GENAI_ROOT")
	if root == "" {
		fmt.Fprintln(os.Stderr, "error: OPENVINO_GENAI_ROOT environment variable is not set.")
		fmt.Fprintln(os.Stderr, "Set it to the root of the extracted OpenVINO GenAI SDK, e.g.:")
		fmt.Fprintln(os.Stderr, "  set OPENVINO_GENAI_ROOT=C:\\openvino_genai_windows_2026.0.0.0_x86_64\\openvino_genai_windows_2026.0.0.0_x86_64")
		os.Exit(1)
	}

	includeDir := filepath.Join(root, "runtime", "include")

	arch := "intel64"
	if runtime.GOOS == "darwin" {
		arch = "arm64"
	}
	libDir := filepath.Join(root, "runtime", "lib", arch, "Release")

	// Validate that the SDK directories exist.
	if _, err := os.Stat(includeDir); err != nil {
		fmt.Fprintf(os.Stderr, "error: include directory not found: %s\n", includeDir)
		os.Exit(1)
	}
	if _, err := os.Stat(libDir); err != nil {
		fmt.Fprintf(os.Stderr, "error: library directory not found: %s\n", libDir)
		os.Exit(1)
	}

	// Use forward slashes — gcc/ld accept them on Windows and they avoid
	// backslash-escaping issues in CGo flag parsing.
	includeDir = strings.ReplaceAll(includeDir, "\\", "/")
	libDir = strings.ReplaceAll(libDir, "\\", "/")

	const code = `//go:build openvino

// Code generated by generate_cgo_flags.go; DO NOT EDIT.
// Re-generate with: go generate ./openvino/...

package openvino

// #cgo CFLAGS: -I%s
// #cgo LDFLAGS: -L%s -lopenvino_genai_c -lopenvino_c
import "C"
`

	out, err := os.Create("cgo_flags_generated.go")
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: cannot create cgo_flags_generated.go: %v\n", err)
		os.Exit(1)
	}
	defer out.Close()

	fmt.Fprintf(out, code, includeDir, libDir)
	fmt.Println("openvino: generated cgo_flags_generated.go")
	fmt.Printf("  CFLAGS:  -I%s\n", includeDir)
	fmt.Printf("  LDFLAGS: -L%s -lopenvino_genai_c -lopenvino_c\n", libDir)
}
